title: Woorak Choi
description: Ph.D. - Department of Astronomy, Yonsei University
site_title: '@wrchoi - Woorak Choi'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: woorak-choi
blog_url: 
email: woorak.c@gmail.com

# absolute or relative
profile_picture: assets/images/2018내사진.jpg

# Google Analytics ID
google_analytics: 
